config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'dang-nhap', sign_out: 'dang-xuat', sign_up: 'dang-ky' },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root to: "home#index"

  get 'get_district_list', to: "application#get_districts"
  get 'get_commune_list', to: "application#get_communes"
  get 'manage', to: "manage#index"
  get 'sale', to: "sale#index"
  get 'dashboard', to: "sale#dashboard"
  get 'get_current_user', to: "application#get_current_user"
  get 'bang-gia', to: "home#pricing", as: :pricing

  scope :manage do
    resources :invoices
    resources :products do
      member do
        get 'update_status'
      end
    end
    resources :customers do
      collection do
        get 'search'
      end
    end
    resources :suppliers do
      collection do
        get 'search'
      end
    end
    resources :product_groups
    resources :producers

    resources :purchase_orders do
      member do
        post 'status'
        get 'pdf'
      end
    end
    resources :product_purchase_orders

    resources :users
    resources :roles
    resources :purchases
    resources :reports
    resources :print_templates
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable, :recoverable, :rememberable, :trackable, :validatable

  has_one_attached :avatar
  has_many :stores
  belongs_to :province, optional: true
  belongs_to :district, optional: true
  belongs_to :commune, optional: true
  has_many :members, dependent: :delete_all

  enum status: { active: 0, inactive: 1, archived: 2 }

  attr_accessor :login

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      store_params = { user_id: resource.id, address: resource.address, province_id: resource.province_id, district_id: resource.district_id }
      store = Store.new(new_store_params.merge(store_params))
      store.save

      # Create default role
      role = Role.new(store_id: store.id, name: "Nhân viên", permissions: Role.default_permissions)
      role.save

      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end

  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :email, :phone, :username, :province_id, :district_id, :address])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    # super(resource)
    manage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def new_store_params
    params.require(:store).permit(:name, :email, :address, :province_id, :district_id, :user_id, :store_type_id, :store_kind_id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  layout 'devise'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super do |resource|
      if params[:type].present? && params[:type].eql?("sale")
        respond_with resource, location: sale_path
      else
        respond_with resource, location: manage_path
      end
      return
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :destroy, :edit, :update]
  require 'will_paginate/array'

  def index
    unless has_permission?("user_view")
      render "roles/no_permission", layout: 'home'
      return
    end

    @per_page = params[:per_page] || User.per_page || 20
    @users = current_store.members.map{|m| m.user}.paginate(:page => params[:page], :per_page => @per_page)
  end

  def new
    unless has_permission?("user_new")
      render "roles/no_permission", layout: 'home'
      return
    end

    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @member = Member.new(member_params)
      @member.user_id = @user.id # Set member for this user
      @member.store = current_store
      @member.save

      redirect_to users_path
    end
  end

  def show
    unless has_permission?("user_view")
      render "roles/no_permission", layout: 'home'
    end
  end

  def edit
    if @user != current_user
      unless has_permission?("user_edit")
        render "roles/no_permission", layout: 'home'
      end
    end
  end

  def update
    if params[:user].present?
      # Update My Account
      if @user == current_user
        change_password = true
        if params[:user][:current_password].blank? || params[:user][:password].blank?
          params[:user].delete(:current_password)
          params[:user].delete(:password)
          params[:user].delete(:password_confirmation)
          change_password = false
        end

        if change_password
          if @user.update_with_password(user_params)
            bypass_sign_in(@user)
          end
        else
          @user.update(user_params)
        end
      else
        # Update user in store
        if params[:user][:password].blank?
          params[:user].delete(:password)
          params[:user].delete(:password_confirmation)
        end

        if @user.update(user_params)
          member = current_store.members.where(user_id: @user.id).first
          member.update(member_params)
          # Should logout member and must re-login
          redirect_to users_path, notice: "Cập nhật người dùng thành công"
        end
      end
    else
      # That case only update role for member
      member = current_store.members.where(user_id: @user.id).first
      member.update(member_params)
      redirect_to users_path, notice: "Cập nhật vai trò thành công"

      # Should logout member and must re-login
    end
  end

  def destroy
    unless has_permission?("user_delete")
      render "roles/no_permission", layout: 'home'
      return
    end

    if current_store.user == @user
      redirect_to users_path, alert: "Bạn không thể xóa người dùng này"
    else
      @user.status = :archived
      if @user.save
        redirect_to users_path
      else
        redirect_to users_path, alert: "Có lỗi khi xóa người dùng này. Vui lòng thử lại"
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:fullname, :username, :email, :password, :password_confirmation, :current_password, :phone, :birthday, :province_id, :district_id, :commune_id, :address)
  end

  def member_params
    params.require(:member).permit(:user_id, :store_id, :role_id, :branch_id)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<div class="new-customer">
  <%= form_with model: user, id: 'new-member' do |f| %>
    <div class="row">
      <div class="col-md-6">

        <div class="form-group">
          <%= f.label :fullname, class: "col-form-label font-weight-bold" %>
          <%= f.text_field :fullname, class: "form-control form-control-sm", placeholder: t('.fullname_placeholder'), required: true %>
        </div>

        <div class="form-group">
          <%= f.label :username, class: "col-form-label font-weight-bold" %>
          <%= f.text_field :username, class: "form-control form-control-sm", placeholder: t('.username_placeholder') %>
        </div>

        <div class="form-group">
          <%= f.label :email, class: "col-form-label font-weight-bold" %>
          <%= f.email_field :email, class: "form-control form-control-sm", placeholder: t('.email_placeholder') %>
        </div>

        <div class="form-row">
          <div class="col">
            <%= f.label :password, class: "col-form-label font-weight-bold" %>
            <% if @minimum_password_length %>
              <em>(ít nhất <%= @minimum_password_length %> ký tự)</em>
            <% end %><br/>
            <%= f.password_field :password, autocomplete: "off", class: "form-control form-control-sm", required: user.new_record? ? true : false %>
          </div>
          <div class="col">
            <%= f.label :password_confirmation, class: "col-form-label font-weight-bold" %>
            <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control form-control-sm", required: user.new_record? ? true : false %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :role, class: "col-form-label font-weight-bold" %>
          <% roles = current_store.roles.collect{|role| [role.name, role.id]} %>
          <% role = current_store.members.where(user_id: user.id).first.role unless user.new_record? %>
          <%= select_tag 'member[role_id]', options_for_select(roles, role.present? ? role.id : ""), prompt: t(:prompt_role), class: "form-control form-control-sm", required: true%>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :phone, class: "col-form-label font-weight-bold" %>
          <%= f.phone_field :phone, class: "form-control form-control-sm", placeholder: t('.phone_placeholder') %>
        </div>

        <div class="form-group">
          <%= f.label :birthday, class: "col-form-label font-weight-bold mr-3" %>
          <div class="input-group">
            <%= f.date_select :birthday, {order: [:day, :month, :year], prompt: { day: 'Ngày', month: 'Tháng', year: 'Năm' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {class: "form-control form-control-sm d-inline-block"} %>
          </div>
        </div>

        <div class="form-row">
          <div class="col">
            <%= f.label t(:label_province), class: "col-form-label font-weight-bold" %>
            <%= f.select :province_id, options_for_select(Province.all.collect{|province| [province.name, province.id]}, user.province_id.present? ? user.province_id : ''), {prompt: t(:prompt_province_select)}, class: "form-control form-control-sm" %>
          </div>
          <div class="col">
            <%= f.label t(:label_district), class: "col-form-label font-weight-bold" %>
            <%= f.select :district_id, [], {prompt: t(:prompt_district_select)}, class: "form-control form-control-sm" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t(:label_commune), class: "col-form-label font-weight-bold" %>
          <%= f.select :commune_id, [], {prompt: t(:prompt_commune_select)}, class: "form-control form-control-sm" %>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "col-form-label font-weight-bold" %>
          <%= f.text_field :address, class: "form-control form-control-sm", placeholder: t('.address_placeholder') %>
        </div>
      </div>

      <%= f.submit t(:save), class: 'd-none' %>
    </div>

  <% end %>
</div>

<script>
    $(document).ready(function () {
        'use strict';

        let province = $('#user_province_id').val();
        if (province) {
            getDistrictAndCommuneOptions(province);
        }

        $('#user_province_id').on('change', function () {
            let province_id = this.value;
            getDistrictOption(province_id);
        });

        $('#user_district_id').on('change', function () {
            let district_id = this.value;
            getCommuneOptions(district_id);
        });

        $('#submit_add_member_btn').click(function () {
            $('#new-member').find('[type="submit"]').trigger('click');
        });

        function getDistrictOption(province_id) {
            $.ajax({
                url: '/get_district_list',
                data: {
                    province_id: province_id
                },
                success: function (data) {
                    $('#user_district_id').html(data);
                    if (!province_id) {
                        $('#user_district_id').html('<option value=""><%= t(:prompt_district_select) %></option>');
                    }
                }
            });
        }

        function getCommuneOptions(district_id) {
            $.ajax({
                url: '/get_commune_list',
                data: {
                    district_id: district_id
                },
                success: function (data) {
                    $('#user_commune_id').html(data);
                    if (!district_id) {
                        $('#user_commune_id').html('<option value=""><%= t(:prompt_commune_select) %></option>');
                    }
                }
            });
        }

        function getDistrictAndCommuneOptions(province_id) {
            $.ajax({
                url: '/get_district_list',
                data: {
                    province_id: province_id
                },
                success: function (data) {

                    if (!province_id) {
                        $('#user_district_id').html('<option value=""><%= t(:prompt_district_select) %></option>');
                    } else {
                        $('#user_district_id').html(data);
                        $('#user_district_id').find('option[value=<%= user.district_id %>]').attr('selected',true);
                    }

                    let district_id = $('#user_district_id').val();
                    if (district_id) {
                        $.ajax({
                            url: '/get_commune_list',
                            data: {
                                district_id: district_id
                            },
                            success: function (data) {
                                if (!district_id) {
                                    $('#user_commune_id').html('<option value=""><%= t(:prompt_commune_select) %></option>');
                                } else {
                                    $('#user_commune_id').html(data);
                                    $('#user_commune_id').find('option[value=<%= user.commune_id %>]').attr('selected', true);
                                }
                            }
                        });
                    }
                }
            });
        }
    })
</script>

app/views/users/_user_information.html.erb
<div class="row mb-3">
  <div class="col-md-4 col-sm-6">
    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.username') %></div>
      <div class="col-8 font-weight-bold"><%= @user.username %></div>
    </div>

    <hr>

    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.fullname') %></div>
      <div class="col-8 font-weight-bold"><%= @user.fullname %></div>
    </div>

    <hr>

    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.phone') %></div>
      <div class="col-8 font-weight-bold"><%= @user.phone %></div>
    </div>

    <hr>

    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.birthday') %></div>
      <div class="col-8 font-weight-bold"><%= @user.birthday %></div>
    </div>


  </div>

  <div class="col-md-4 col-sm-6">
    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.email') %></div>
      <div class="col-8 font-weight-bold"><%= @user.email %></div>
    </div>

    <hr>

    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.address') %></div>
      <div class="col-8 font-weight-bold"><%= @user.address %></div>
    </div>

    <hr>

    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.area') %></div>
      <div class="col-8 font-weight-bold"><%= @user.province.name if @user.province %> - <%= @user.district.name if @user.district %></div>
    </div>

    <hr>

    <div class="row">
      <div class="col-4"><%= t('activerecord.attributes.user.commune') %></div>
      <div class="col-8 font-weight-bold"><%= @user.commune.name if @user.commune %></div>
    </div>

  </div>


</div>


<div class="nav-item float-right">
  <%= link_to fa_icon(:edit, text: t(:update)), edit_user_path(@user), remote: true, class: "btn btn-success" %>

  <%= link_to fa_icon("trash", text: t(:delete)), user_path(@user), method: :delete, data: { confirm: "Bạn có chắc chắn muốn xóa yêu cầu này ?" }, class: "btn btn-danger" %>
</div>

app/views/users/_user_role.html.erb
<div class="row">
  <div class="col-1">Vai trò</div>

  <div class="col-3">
    <% roles = current_store.roles.collect{|role| [role.name, role.id]} %>
    <% role = current_store.members.where(user_id: @user.id).first.role %>
    <%= form_with model: @user, id: 'update_member' do |f| %>
      <%= select_tag 'member[role_id]', options_for_select(roles, role.present? ? role.id : ""), prompt: t(:prompt_role), class: "form-control form-control-sm"%>
      <br>
      <%= f.submit t(:save), class: "btn btn-success" %>
    <% end %>

  </div>
  <div class="col">
    <div class="float-right">
      <%= link_to fa_icon("edit", text: t(:edit)), role.present? ? edit_role_path(role, user_id: @user.id) : "#", class: "btn btn-success", id: "edit_role", remote: true %>
      <%= link_to fa_icon("paste", text: "Lưu thành vai trò mới"), "", class: "btn btn-info d-none" %>
      <%= link_to fa_icon("plus", text: "Thêm vai trò mới"), new_role_path(user_id: @user.id), class: "btn btn-park text-white", remote: true %>
    </div>
  </div>
</div>

<div>
  
</div>

<script>
  $(document).ready(function () {
      let current_user_id = <%= @user.id %>;
      $('#member_role_id').on('change', function() {
          if (this.value) {
              $("#edit_role").attr("href", "/manage/roles/" + this.value + "/edit?user_id=" + current_user_id)
          } else {
              $("#edit_role").attr("href", "#");
              toastr.error("Vui lòng chọn một vai trò trước khi sửa.")
          }

          // Submit when change role
          // $('#update_member').find('[type="submit"]').trigger('click');
      });
  })
</script>

app/views/users/create.js.erb
<% if @user.errors.present? %>
  toastr.error("<%= @user.errors.full_messages.to_sentence %>");
<% end %>

app/views/users/edit.js.erb
<% if user_signed_in? %>
  <% if @user == current_user %>
    var message = "<%= j render :partial => 'users/form_owner', locals: {user: @user} %>";
  <% else %>
    var message = "<%= j render :partial => 'users/form', locals: {user: @user} %>";
  <% end %>
  message = message.replace(/(?:\r\n|\r|\n)/g, '');
  var modal = "<%= j render :partial => 'shared/modal_submit', locals: {title: t(:edit_member), submit_id: 'submit_add_member_btn'} %>";
  modal = modal.replace(/(?:\r\n|\r|\n)/g, '');
  $("body").append(modal);
  $(".modal-body").html(message);
  $("#park-modal").modal({
      backdrop: 'static',
      keyboard: false
  });
<% end %>

app/views/users/index.html.erb
<div class="products">
  <div class="header">
    <nav class="navbar navbar-expand navbar-light bg-light">
      <div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <span class="title"><%= t('.user_list') %></span>
          </li>
        </ul>
      </div>
      <div class="mx-auto order-0">

      </div>
      <div class="navbar-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to new_user_path, class: "btn btn-info header-menu", remote: true do %>
              <%= fa_icon "plus", text: t('add_new_member') %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </div>


  <div class="notification">
    <% if @users.size == 0 %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        Chưa có người dùng nào. Vui lòng chọn <strong>"<%= t('.add_new_member') %>"</strong> để thêm người dùng mới!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>

  <div class="list">
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
      <th>Tên đăng nhập</th>
      <th>Tên người dùng</th>
      <th>Vai trò</th>
      <th>Số điện thoại</th>
      <th></th>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username, user_path(user) %></td>
          <td><%= user.fullname %></td>
          <td><%= current_store.members.where(user_id: user.id).first.role.name if current_store.members.where(user_id: user.id).present? && current_store.members.where(user_id: user.id).first.role.present? %></td>
          <td><%= user.phone %></td>
          <td>
            <%= link_to fa_icon("pencil", class: "btn btn-success"), edit_user_path(user), remote: true %>
            <%= link_to fa_icon("trash", class: "btn btn-danger"), user_path(user), method: :delete, class: "text-danger", data: { confirm: "Bạn có chắc chắn muốn xóa yêu cầu này ?" } %>
          </td>
        </tr>
      <% end %>
      </tbody>

      <tfoot>
      <tr>
        <td colspan="6">
          <%= render partial: 'shared/pagination_footer_table', locals: {objects: @users} %>
        </td>
      </tr>
      </tfoot>
    </table>
  </div>

</div>

app/views/users/new.js.erb
<% if user_signed_in? %>
var message = "<%= j render :partial => 'users/form', locals: {user: @user} %>";
message = message.replace(/(?:\r\n|\r|\n)/g, '');
var modal = "<%= j render :partial => 'shared/modal_submit', locals: {title: t(:add_new_member), submit_id: 'submit_add_member_btn'} %>";
modal = modal.replace(/(?:\r\n|\r|\n)/g, '');
$("body").append(modal);
$(".modal-body").html(message);
$("#park-modal").modal({
    backdrop: 'static',
    keyboard: false
});
<% end %>

app/views/users/show.html.erb
<div class="m-3 product">
  <div class="card">
    <div class="card-header">
      <h5 class="product-name font-weight-bold mb-0"><%= @user.fullname %></h5>
    </div>
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs" role="tab">
        <li class="nav-item">
          <a class="nav-link active" href="#information-content" data-toggle="tab" role="tab"aria-controls="information" aria-selected="true" >
            <%= fa_icon("info-circle", text: t('.tab_information')) %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#role-content" data-toggle="tab" role="tab"aria-controls="role" aria-selected="true">
            <%= fa_icon("server", text: t('.tab_role')) %>
          </a>
        </li>

      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content">
        <div class="tab-pane fade show active" id="information-content" role="tabpanel" aria-labelledby="information-tab">
          <%= render 'user_information' %>
        </div>

        <div class="tab-pane fade show" id="role-content" role="tabpanel" aria-labelledby="role-tab">
          <%= render 'user_role' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
<% if @user == current_user %>
  <% if @user.errors.present? %>
    toastr.error("<%= @user.errors.full_messages.to_sentence %>");
  <% else %>
    $('#park-modal').modal('toggle');
    toastr.success("Cập nhật tài khoản thành công");
  <% end %>
<% else %>
  <% if @user.errors.present? %>
    toastr.error("<%= @user.errors.full_messages.to_sentence %>");
  <% end %>
<% end %>