config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'dang-nhap', sign_out: 'dang-xuat', sign_up: 'dang-ky' },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root to: "home#index"

  get 'get_district_list', to: "application#get_districts"
  get 'get_commune_list', to: "application#get_communes"
  get 'manage', to: "manage#index"
  get 'sale', to: "sale#index"
  get 'dashboard', to: "sale#dashboard"
  get 'get_current_user', to: "application#get_current_user"
  get 'bang-gia', to: "home#pricing", as: :pricing

  scope :manage do
    resources :invoices
    resources :products do
      member do
        get 'update_status'
      end
    end
    resources :customers do
      collection do
        get 'search'
      end
    end
    resources :suppliers do
      collection do
        get 'search'
      end
    end
    resources :product_groups
    resources :producers

    resources :purchase_orders do
      member do
        post 'status'
        get 'pdf'
      end
    end
    resources :product_purchase_orders

    resources :users
    resources :roles
    resources :purchases
    resources :reports
    resources :print_templates
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    unless has_permission?("purchase_view")
      render "roles/no_permission", layout: 'home'
      return
    end

    @per_page = params[:per_page] || Purchase.per_page || 20
    @q = Purchase.ransack(params[:q])
    @purchases = @q.result.by_store(current_store.id).order('id desc').paginate(:page => params[:page], :per_page => @per_page)
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    unless has_permission?("purchase_view")
      render "roles/no_permission", layout: 'home'
    end
  end

  # GET /purchases/new
  def new
    unless has_permission?("purchase_new")
      render "roles/no_permission", layout: 'home'
      return
    end

    @purchase = Purchase.new
    @purchase.date = Date.today
    @purchase.time =  Time.now.strftime('%H:%M') #  Time.now.strftime('%H:%M')
    @users = ([current_user] + current_store.members.map{|m| m.user}).uniq
    @suppliers = Supplier.by_store(current_store.id)

    # Copy data from PPO
    if params[:purchase_order_id].present?
      purchase_order = PurchaseOrder.find(params[:purchase_order_id])
      if purchase_order.store == current_store
        @purchase.purchase_order_id = purchase_order.id
        @purchase.supplier = purchase_order.supplier
        @purchase.user = current_user
        @purchase.purchaser = current_user
        @purchase.store = current_store

        if @purchase.save
          @purchase.code = build_code("PC", @purchase) unless @purchase.code.present?

          purchase_order.product_purchase_orders.each do |ppo|
            pp = ProductPurchase.new
            pp.purchase = @purchase
            pp.product = ppo.product
            pp.quantity = ppo.quantity.present? ? ppo.quantity : 0
            pp.unit_price = ppo.unit_price.present? ? ppo.unit_price : 0
            pp.discount_percent = ppo.discount_percent.present? ? ppo.discount_percent : 0
            pp.discount_money = ppo.discount_money.present? ? ppo.discount_money : 0
            pp.final_price = ppo.total_price
            pp.save
          end

          @purchase.update_price
          @purchase.save
        end
      end
    end
  end

  # GET /purchases/1/edit
  def edit
    unless has_permission?("purchase_edit")
      render "roles/no_permission", layout: 'home'
      return
    end

    @purchase = Purchase.find(params[:id])
    @users = ([current_user] + current_store.members.map{|m| m.user}).uniq
    @suppliers = Supplier.by_store(current_store.id)
  end

  # POST /purchases
  # POST /purchases.json
  def create
    # Remove template row data
    params[:purchase][:product_purchases_attributes].shift if params[:purchase].present? && params[:purchase][:product_purchases_attributes].present?

    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user
    @purchase.purchaser = current_user
    @purchase.store = current_store

    if params[:type].eql?("purchase")
      @purchase.status = :purchased
    end

    respond_to do |format|
      if @purchase.save

        @purchase.code = build_code("PC", @purchase) unless @purchase.code.present?

        total = 0
        @purchase.product_purchases.each do |pp|
          final_price = pp.quantity * pp.unit_price - pp.discount_money
          pp.final_price = final_price
          total += final_price
          pp.save
        end

        @purchase.discount_money = 0 if @purchase.discount_money.nil?
        @purchase.paid = 0 if @purchase.paid.nil?
        @purchase.total_price = total
        @purchase.price = total - @purchase.discount_money
        @purchase.dept = @purchase.paid + @purchase.discount_money - total
        @purchase.save

        format.html { redirect_to @purchase, notice: 'Tạo đơn nhập hàng thành công.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    # Remove template row data
    params[:purchase][:product_purchases_attributes].shift if params[:purchase].present? && params[:purchase][:product_purchases_attributes].present?
    new_pps = params[:purchase][:product_purchases_attributes].map{|pp| pp['id'].to_i}

    respond_to do |format|
      if @purchase.update(purchase_params)
        @purchase.product_purchases.each do |pp|
          # Delete removed item or update price
          if new_pps.include?(pp.id)
            pp.final_price = pp.quantity * pp.unit_price - pp.discount_money
            pp.save
          else
            pp.destroy
          end
        end

        total = 0
        @purchase.product_purchases.each do |pp|
          total += pp.final_price
        end
        @purchase.total_price = total
        @purchase.price = total - @purchase.discount_money
        @purchase.dept = @purchase.paid + @purchase.discount_money - total
        @purchase.save

        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    unless has_permission?("purchase_delete")
      render "roles/no_permission", layout: 'home'
      return
    end

    @purchase.status = :cancel
    if @purchase.save
      respond_to do |format|
        format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:name, :purchaser_id, :supplier_id, :code, :discount_money, :paid, :note, :date, :time, :purchase_order_id, product_purchases_attributes: [:id, :product_id, :purchase_id, :quantity, :unit_price, :discount_percent, :discount_money, :final_price])
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/create.js.erb
<% if @purchase.errors.present? %>
  toastr.error("<%= @purchase.errors.full_messages.to_sentence %>");
<% end %>

app/views/purchases/create_supplier.js.erb
$('#park-modal').modal('toggle');

$("#purchase_supplier_id").append($('<option>', {
    value: 10,
    text: 'Hichic'
}));

$("#purchase_supplier_id").val(10);

app/views/purchases/edit.html.erb
<%= render 'form', purchase: @purchase %>

app/views/purchases/index.html.erb
<div class="products">
  <div class="header">
    <nav class="navbar navbar-expand navbar-light bg-light">
      <div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <span class="title"><%= t('activerecord.attributes.purchase.title') %></span>
          </li>
        </ul>
      </div>
      <div class="mx-auto order-0">

      </div>
      <div class="navbar-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to new_purchase_path, class: "btn btn-success header-menu" do %>
              <%= fa_icon "plus", text: t('.add_purchase') %>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_purchase_path, class: "btn btn-info header-menu" do %>
              <%= fa_icon "download", text: "Xuất excel" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </div>


  <div class="notification">
    <% if @purchases.size == 0 %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        Chưa có nhập hàng nào. Vui lòng chọn <strong>"<%= t('.add_purchase') %>"</strong> để thêm mới!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>

  <div class="search">
    <div class="col-md-6">
      <%= search_form_for @q, url: purchases_path, method: :get do |f| %>
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text"><%= t(:search) %></div>
          </div>
          <%= f.text_field :code, placeholder: t('.search_placeholer'), class: "form-control" %>
          <div class="input-group-append">
            <%= f.submit t(:search), class: "btn btn-info btn-park" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="list">
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
      <th><%= sort_link @q, :code, t('activerecord.attributes.purchase.code'), default_order: :desc %></th>
      <th><%= t('activerecord.attributes.purchase_order.code') %></th>
      <th><%= t('activerecord.attributes.purchase.date') %></th>
      <th><%= sort_link @q, :supplier, t('activerecord.attributes.purchase.supplier') %></th>
      <th><%= sort_link @q, :price, t('activerecord.attributes.purchase.price') %></th>
      <th><%= sort_link @q, :status, t('activerecord.attributes.purchase.status') %></th>
      </thead>

      <tbody>
      <% @purchases.each do |purchase| %>
        <tr>
          <td>
            <%= link_to purchase.code, purchase_path(purchase) %>
          </td>
          <td>
            <%= link_to purchase.purchase_order.code, purchase.purchase_order if purchase.purchase_order %>
          </td>
          <td>
            <%= "#{purchase.date} #{purchase.time.strftime('%H:%M') if purchase.time}"  %>
          </td>
          <td>
            <%= purchase.supplier.name if purchase.supplier.present? %>
          </td>
          <td>
            <%= number_to_dong(purchase.price) %>
          </td>
          <td class="purchase-status-<%= purchase.status %>">
            <%= Purchase.human_enum_name(:status, purchase.status) %>
          </td>
        </tr>
      <% end %>
      </tbody>

      <tfoot>
      <tr>
        <td colspan="6">
          <%= render partial: 'shared/pagination_footer_table', locals: {objects: @purchases} %>
        </td>
      </tr>
      </tfoot>
    </table>
  </div>

</div>

app/views/purchases/new.html.erb
<%= render 'form', purchase: @purchase %>

app/views/purchases/show.html.erb
<div class="m-3 product">
  <div class="card">
    <div class="card-header">
      <h5 class="product-name font-weight-bold mb-0">#<%= @purchase.code %> <%= @purchase.name if @purchase.name.present? %></h5>
    </div>
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs" role="tab">
        <li class="nav-item">
          <a class="nav-link active" href="#information-content" data-toggle="tab" role="tab"aria-controls="information" aria-selected="true" >
            <%= fa_icon("info-circle", text: t('.tab_information')) %>
          </a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content">
        <div class="tab-pane fade show active" id="information-content" role="tabpanel" aria-labelledby="information-tab">

          <div class="row mb-3">
            <div class="col-md-4 col-sm-6">
              <div class="row">
                <div class="col-4"><%= t('activerecord.attributes.purchase.code') %></div>
                <div class="col-8 font-weight-bold"><%= @purchase.code %></div>
              </div>

              <hr>

              <div class="row">
                <div class="col-4"><%= t('activerecord.attributes.purchase.date') %></div>
                <div class="col-8 font-weight-bold"><%= @purchase.date %></div>
              </div>

              <hr>

              <div class="row">
                <div class="col-4"><%= t('activerecord.attributes.purchase.supplier') %></div>
                <div class="col-8 font-weight-bold"><%= link_to @purchase.supplier.name, supplier_path(@purchase.supplier) if @purchase.supplier.present? %></div>
              </div>

            </div>

            <div class="col-md-4 col-sm-6">
              <div class="row">
                <div class="col-4"><%= t('activerecord.attributes.purchase.status') %></div>
                <div class="col-8 font-weight-bold"><%= Purchase.human_enum_name(:status, @purchase.status) %></div>
              </div>

              <hr>

              <div class="row">
                <div class="col-4"><%= t('activerecord.attributes.purchase.user') %></div>
                <div class="col-8 font-weight-bold"><%= @purchase.user.fullname if @purchase.user.present? %></div>
              </div>

              <hr>

              <div class="row">
                <div class="col-4"><%= t('activerecord.attributes.purchase.purchaser') %></div>
                <div class="col-8 font-weight-bold"><%= @purchase.purchaser.fullname if @purchase.purchaser.present? %></div>
              </div>

            </div>

            <div class="col-md-4">
              <div>Ghi chú</div>
              <div><%= @purchase.note %></div>
            </div>
          </div>

          <div class="mb-3">
            <table class="table table-bordered">
              <thead>
              <th><%= t('activerecord.attributes.product.code') %></th>
              <th><%= t('activerecord.attributes.product.name') %></th>
              <th><%= t('activerecord.attributes.product.quantity') %></th>
              <th><%= t('activerecord.attributes.product.unit_price') %></th>
              <th><%= t('activerecord.attributes.product.discount_money') %></th>
              <th><%= t('activerecord.attributes.product.final_price') %></th>
              </thead>
              <tbody>
                <% total_quantity = 0 %>
                <% @purchase.product_purchases.each do |pp| %>
                  <% total_quantity += pp.quantity %>
                  <tr>
                    <td><%= pp.product.code %></td>
                    <td><%= pp.product.name %></td>
                    <td><%= pp.quantity %></td>
                    <td><%= number_to_dong(pp.unit_price) %></td>
                    <td><%= number_to_dong(pp.discount_money) %></td>
                    <td><%= number_to_dong pp.final_price %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="row">
            <div class="col">
              <table class="table table-borderless float-right" style="width: 400px">
                <tr>
                  <td class="text-right">Tổng số lượng hàng</td>
                  <td class="text-right"><%= total_quantity %></td>
                </tr>
                <tr>
                  <td class="text-right">Tổng số mặt hàng</td>
                  <td class="text-right"><%= @purchase.product_purchases.size %></td>
                </tr>
                <tr>
                  <td class="text-right">Tổng tiền hàng</td>
                  <td class="text-right"><%= number_to_dong(@purchase.total_price) %></td>
                </tr>
                <tr>
                  <td class="text-right">Giảm giá</td>
                  <td class="text-right"><%= number_to_currency(@purchase.discount_money, precision: 0, unit: '') %></td>
                </tr>
                <tr>
                  <td class="text-right">Cần trả nhà cung cấp</td>
                  <td class="text-right"><%= number_to_currency(@purchase.price, precision: 0, unit: '') %></td>
                </tr>
                <tr>
                  <td class="text-right">Đã trả nhà cung cấp</td>
                  <td class="text-right"><%= number_to_currency(@purchase.paid, precision: 0, unit: '') %></td>
                </tr>
              </table>
            </div>
          </div>

          <div class="nav-item float-right">
            <%= link_to fa_icon(:edit, text: t(:update)), edit_purchase_path(@purchase), class: "btn btn-success" %>

            <%= link_to fa_icon("trash", text: t(:cancel)), purchase_path(@purchase), method: :delete, data: { confirm: "Bạn có chắc chắn muốn xóa yêu cầu này ?" }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/purchases/update.js.erb
<% if @purchase.errors.present? %>
  toastr.error("<%= @purchase.errors.full_messages.to_sentence %>");
<% end %>