config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'dang-nhap', sign_out: 'dang-xuat', sign_up: 'dang-ky' },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root to: "home#index"

  get 'get_district_list', to: "application#get_districts"
  get 'get_commune_list', to: "application#get_communes"
  get 'manage', to: "manage#index"
  get 'sale', to: "sale#index"
  get 'dashboard', to: "sale#dashboard"
  get 'get_current_user', to: "application#get_current_user"
  get 'bang-gia', to: "home#pricing", as: :pricing

  scope :manage do
    resources :invoices
    resources :products do
      member do
        get 'update_status'
      end
    end
    resources :customers do
      collection do
        get 'search'
      end
    end
    resources :suppliers do
      collection do
        get 'search'
      end
    end
    resources :product_groups
    resources :producers

    resources :purchase_orders do
      member do
        post 'status'
        get 'pdf'
      end
    end
    resources :product_purchase_orders

    resources :users
    resources :roles
    resources :purchases
    resources :reports
    resources :print_templates
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
    end
  end
end

app/views/shared/_footer_home.html.erb
<footer>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_message_html.html.erb
<% flash.each do |name, msg| %>
  <% if msg.class == Array %>
    <% msg.each do |message| %>
      <%= content_tag :div, message, :id => "flash_#{name}" %>
    <% end %>
  <% else %>
    <%= content_tag :div, msg, :id => "flash_#{name}", class: "my-3 text-danger" %>
  <% end %>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="park-modal" tabindex="-1" role="dialog" aria-labelledby="park-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <% if title.present? %>
          <h5 class="modal-title" id="park-modal-title"><%= title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(:close) %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_submit.html.erb
<div class="modal fade" id="park-modal" tabindex="-1" role="dialog" aria-labelledby="park-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <% if title.present? %>
          <h5 class="modal-title" id="park-modal-title"><%= title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(:close) %></button>
        <button type="button" class="btn btn-success" id="<%= submit_id %>"><%= fa_icon "floppy-o", text: t(:save) %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_submit_delete.html.erb
<div class="modal fade" id="park-modal" tabindex="-1" role="dialog" aria-labelledby="park-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <% if title.present? %>
          <h5 class="modal-title" id="park-modal-title"><%= title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(:close) %></button>
        <button type="button" class="btn btn-success" id="<%= submit_id %>"><%= fa_icon "floppy-o", text: t(:save) %></button>
        <button type="button" class="btn btn-danger" id="<%= delete_id %>"><%= fa_icon "trash", text: t(:delete) %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_submit_large.html.erb
<div class="modal fade" id="park-modal" tabindex="-1" role="dialog" aria-labelledby="park-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <% if title.present? %>
          <h5 class="modal-title" id="park-modal-title"><%= title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(:close) %></button>
        <button type="button" class="btn btn-success" id="<%= submit_id %>"><%= fa_icon "floppy-o", text: t(:save) %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-park">
  <a class="navbar-brand" href="<%= manage_path %>">Park Việt</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mx-auto">
      <div class="d-flex justify-content-center help-text-login">
        <%= link_to fa_icon("phone", text: "Hỗ trợ"), "#", class: "help-text-login" %>
        <span class="help-text-login">|</span>
        <%= link_to fa_icon("laptop", text: "Tải Teamviewer"), "#", class: "help-text-login" %>
        <span class="help-text-login">|</span>
        <div class="help-text-login"><%= fa_icon("volume-control-phone", text: "Hotline:") %><span class="help-text-login" style="color: orange;">0349593392</span></div>
      </div>
    </ul>
  </div>

  <div class="navbar-select-branch">
    <%= select_tag  'branch' , options_for_select(["Chi nhánh trung tâm"], "Chi nhánh trung tâm"), class: "form-control form-control-sm"%>
  </div>

  <ul class="navbar-nav manage-navbar">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="setupNavBarMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Thiết lập
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="setupNavBarMenu">
        <%= link_to fa_icon("wrench", text: "Thiết lập cửa hàng"), "#", class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to fa_icon("file-text", text: "Quản lý mẫu in"), print_templates_path, class: "dropdown-item", "data-turbolinks": "false" %>
        <div class="dropdown-divider"></div>
        <%= link_to fa_icon("history", text: "Lịch sử thao tác") , "#", class: "dropdown-item" %>
      </div>
    </li>
  </ul>

  <ul class="navbar-nav manage-navbar">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle navbar-user" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Xin chào, <br>
        <%= current_user.fullname %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to fa_icon("user-circle-o", text:"Tài khoản"), edit_user_path(current_user), class: "dropdown-item", remote: true %>
        <%= link_to fa_icon("flag", text: "Báo cáo"), new_report_path, class: "dropdown-item", remote: true %>
        <div class="dropdown-divider"></div>
        <%= link_to fa_icon("sign-out", text:"Đăng xuất"), destroy_user_session_path, method: :delete, class: "dropdown-item"%>
      </div>
    </li>
  </ul>

</nav>

app/views/shared/_navbar_home.html.erb
<nav class="navbar navbar-home navbar-expand-lg navbar-dark bg-park">
  <a class="navbar-brand" href="#">Park Việt</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= "active" if current_page?(root_path) %>">
        <%= link_to "Trang chủ", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tính năng</a>
      </li>
      <li class="nav-item <%= "active" if current_page?(pricing_path) %>">
        <%= link_to "Bảng giá", pricing_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Thiết bị</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Hỗ trợ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tin tức</a>
      </li>
    </ul>
    <% if user_signed_in? %>
      <%= link_to fa_icon("list", text: "Quản lý"), manage_path, class: "btn btn-info", style: "margin-right: 10px;" %>
      <%= link_to fa_icon("shopping-cart", text: "Bán hàng"), sale_path, class: "btn btn-success" %>
    <% else %>
      <%= link_to "Đăng nhập", new_user_session_path, class: "btn btn-link" %>
      <%= link_to "Đăng ký", new_user_registration_path, class: "btn btn-info" %>
    <% end %>
  </div>
</nav>

app/views/shared/_navbar_sale.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-park">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form col-md-5">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text bg-white border-right-0">
            <%= fa_icon("search") %>
          </span>
        </div>
        <input type="text" class="form-control form-control-sm border-left-0" placeholder="<%= t('.label_search_product') %>" aria-label="Tìm mặt hàng" id="search-product-input" autofocus>
      </div>
    </form>

    <ul class="navbar-nav mx-auto">
      <div class="d-flex justify-content-center help-text-login">
        <%= link_to "Báo cáo", "#", class: "help-text-login" %>
        <span class="help-text-login">|</span>
        <%= link_to "Quản lý", "#", class: "help-text-login" %>
        <span class="help-text-login">|</span>
        <%= link_to "Nhập trả", "#", class: "help-text-login" %>
      </div>
    </ul>

  </div>

  <div>
    <button type="button" class="btn btn-link text-light" onclick="toggleFullScreen()"><%= fa_icon "arrows-alt", id: "btn-fullscreen-sale"%></button>
    <button type="button" class="btn btn-link text-light"><%= fa_icon "question" %></button>
  </div>

  <div class="navbar-select-branch">
    <%= select_tag  'branch' , options_for_select(["Chi nhánh trung tâm"], "Chi nhánh trung tâm"), class: "form-control form-control-sm"%>
  </div>

  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle navbar-user" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Xin chào, <br>
        <%= current_user.fullname %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "Tài khoản", "#", class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Đăng xuất", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
      </div>
    </li>
  </ul>

</nav>

app/views/shared/_pagination_footer_table.html.erb
<div class="d-flex justify-content-between">
  <div class="mt-1"></div>
  <div class="mt-1"><%= page_entries_info objects %></div>
  <div class="d-flex justify-content-end">
    <div><%= will_paginate objects %></div>
    <div class="select-per-page ml-2">
      <%= select_tag :per_page, options_for_select([10,25,50,100], params[:per_page].to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}", class: "form-control" %>
    </div>
  </div>
</div>