config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'dang-nhap', sign_out: 'dang-xuat', sign_up: 'dang-ky' },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root to: "home#index"

  get 'get_district_list', to: "application#get_districts"
  get 'get_commune_list', to: "application#get_communes"
  get 'manage', to: "manage#index"
  get 'sale', to: "sale#index"
  get 'dashboard', to: "sale#dashboard"
  get 'get_current_user', to: "application#get_current_user"
  get 'bang-gia', to: "home#pricing", as: :pricing

  scope :manage do
    resources :invoices
    resources :products do
      member do
        get 'update_status'
      end
    end
    resources :customers do
      collection do
        get 'search'
      end
    end
    resources :suppliers do
      collection do
        get 'search'
      end
    end
    resources :product_groups
    resources :producers

    resources :purchase_orders do
      member do
        post 'status'
        get 'pdf'
      end
    end
    resources :product_purchase_orders

    resources :users
    resources :roles
    resources :purchases
    resources :reports
    resources :print_templates
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # has_paper_trail(meta: { store_id: :store_id })
  belongs_to :user
  belongs_to :store
  belongs_to :product_group, optional: true
  belongs_to :producer, optional: true
  belongs_to :product_type, optional: true
  has_many_attached :images

  validates :name, presence: true, length: {minimum: 2, maximum: 64}
  validates :code, uniqueness: {scope: :store}, length: {minimum: 2, maximum: 32}, :allow_blank => true
  validates :cost_price, numericality: true, :allow_blank => true
  validates :sale_price, numericality: true, :allow_blank => true
  validates :in_stock, numericality: {only_integer: true}, :allow_blank => true
  validates :in_stock_min, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 1000000000}, :allow_nil  => true
  validates :in_stock_max, numericality: {only_integer: true, greater_than: :in_stock_min, less_than: 1000000000}, :allow_nil  => true
  validates :vat, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}, :allow_nil  => true

  enum status: { active: 0, inactive: 1, archived: 2 }

  scope :by_store, -> (store_id) { where(store_id: store_id) }
  self.per_page = 10

  has_many :product_purchase_orders
  has_many :purchase_orders, through: :product_purchase_orders

  has_many :product_purchases
  has_many :purchases, through: :product_purchases

  has_many :product_invoices
  has_many :invoices, through: :product_invoices
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :update_status]
  before_action :authenticate_user!
  def index
    @per_page = params[:per_page] || Product.per_page || 20
    @q = Product.ransack(params[:q])
    @products = @q.result.by_store(current_store.id).paginate(:page => params[:page], :per_page => @per_page)

    respond_to do |format|
      format.html {}
      format.json {
        render json: @products, each_serializer: ProductSerializer
      }
    end
  end

  def new
    @product = Product.new
    @product_groups = ProductGroup.by_store(current_store.id)
    @product_group_options = []
    @product_groups.walk_tree do |group, level|
      @product_group_options << ["#{'--' * level} #{group.name}", group.id]
    end

    @producers = Producer.by_store(current_store.id)
  end

  def show

  end
  
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.store = current_store
    @product.abbr_name = @product.name.to_s.split.map(&:first).join.downcase
    if @product.save
      @product.code = build_code unless @product.code.present?
      @product.save
      if params[:kind].eql?('save')
        redirect_to products_path, notice: t(:notice_create_product_successfully)
      elsif params[:kind].eql?('cont')
        redirect_to new_product_path, notice: t(:notice_create_product_successfully)
      end
    end
  end

  def edit
    @product_groups = ProductGroup.by_store(current_store.id)
    @product_group_options = []
    @product_groups.walk_tree do |group, level|
      @product_group_options << ["#{'--' * level} #{group.name}", group.id]
    end

    @producers = Producer.by_store(current_store.id)
  end

  def update_status
    @product.status = params[:status]
    @product.save
  end

  def update
    @product.code = build_code unless params[:product][:code].present?
    if @product.update(product_params)
      redirect_to products_path, notice: t(:notice_update_product_successfully)
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path, notice: t(:notice_delete_product_successfully)
    end
  end

  private

  def build_code
    "HH"+ @product.id.to_s.rjust(6, '0')
  end

  def product_params
    params.require(:product).permit(:name, :code, :description, :note, :cost_price, :sale_price, :vat, :in_stock, :in_stock_min, :in_stock_max, :producer_id, :product_group_id, :basic_unit, images: [])
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="product">
  <div class="header">

    <ul class="nav nav-tabs new-product-tabs" id="new-product" role="tab">
      <li class="nav-item">
        <a href="#basic-content" id="basic-tab" data-toggle="tab" role="tab" aria-controls="basic" aria-selected="true" class="nav-link active">
          <%= fa_icon "barcode" %> <span class="tab-name"><%= t('.tab_basic_information') %></span>
        </a>
      </li>
      <li class="nav-item">
        <a href="#detail-content" id="detail-tab" data-toggle="tab" role="tab" aria-controls="detail" aria-selected="true" class="nav-link">
          <%= fa_icon "file-text-o" %> <span class="tab-name"><%= t('.tab_detail_information') %></span>
        </a>
      </li>
      <li class="nav-item">
        <a href="#part-content" id="part-tab" data-toggle="tab" role="tab" aria-controls="part" aria-selected="true" class="nav-link">
          <%= fa_icon "info-circle" %> <span><%= t('.tab_product_part') %></span>
        </a>
      </li>


      <li class="nav-item ml-auto">
        <button type="button" class="btn btn-success" id="btn_save_product"><%= fa_icon "floppy-o", text: t(:save_only) %></button>
        <button type="button" class="btn btn-success" id="btn_save_product_and_add_new"><%= fa_icon "floppy-o", text: t(:save_cont) %></button>

        <%= link_to products_path, class: "btn btn-secondary" do %>
          <%= fa_icon "ban", text: t(:cancel) %>
        <% end %>
      </li>

    </ul>

  </div>

  <%= form_with model: @product do |f| %>

    <div class="tab-content">
      <div class="tab-pane fade show active" id="basic-content" role="tabpanel" aria-labelledby="home-tab">
        <%= render 'new_product_basic', f: f, locals: {f: f} %>
      </div>
      <div class="tab-pane fade" id="detail-content" role="tabpanel" aria-labelledby="detail-tab">
        <%= render 'new_product_detail', f: f, locals: {f: f} %>
      </div>
      <div class="tab-pane fade" id="part-content" role="tabpanel" aria-labelledby="part-tab">
        <%= render 'new_product_part', f: f, locals: {f: f} %>
      </div>
    </div>

  <% end %>
</div>

<script defer="defer">
    $(document).ready(function () {
        $("#btn_save_product").click(function () {
            $('#save_only_product').trigger('click');
        });

        $("#btn_save_product_and_add_new").click(function () {
            $('#save_product_and_add_new').trigger('click');
        });

        $("#product_images").change(function () {
            let files = this.files;
            if(!files) return;

            let upload_positions = [];
            for (let i = 1; i <= 5; i++){
                if ($("#preview-image-"+i).html().trim() == "") {
                    upload_positions.push(i);
                }
            }

            let fileArr = Array.from(this.files);

            for (let i = 0; i < upload_positions.length; i++) {
              let image_file = fileArr.shift();
              if (image_file) {
                  showPreview(image_file, upload_positions[i])
              }
            }
        });

        function showPreview(image_file, position) {
              let reader = new FileReader();
              reader.onload = function(e) {
                  if (position === 1) {
                      $('#preview-image-' + position).html('<img src="' + e.target.result + '" class="rounded preview-image-big">');
                  } else {
                      $('#preview-image-' + position).html('<img src="' + e.target.result + '" class="rounded preview-image">');
                  }

              };
              reader.readAsDataURL(image_file);
        }
    })
</script>

app/views/products/_new_product_basic.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :name %> <span style="color: red;">*</span>
      <%= f.text_field :name, class: "form-control form-control-sm", placeholder: t('.placeholder_name'), required: true %>
    </div>

    <div class="form-group">
      <%= f.label :code %>
      <%= f.text_field :code, class: "form-control form-control-sm", placeholder: t('.placeholder_code') %>
    </div>

    <div class="form-group">
      <%= f.label :product_group_id %>
      <div class="input-group">
        <%= f.select :product_group_id, options_for_select(@product_group_options, @product.product_group_id.present? ? @product.product_group_id : ''), {prompt: "-- Chọn nhóm hàng nếu có --"}, {class: "custom-select form-control form-control-sm"} %>
        <div class="input-group-append">
          <%= link_to product_groups_path, class: "btn btn-outline-secondary btn-sm", remote: true do %>
            <%= fa_icon("ellipsis-h") %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :cost_price %>
          <%= f.number_field :cost_price, class: "form-control text-right form-control-sm", placeholder: "Nhập giá vốn" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :sale_price, "Giá bán" %>
          <div class="input-group">
            <%= f.number_field :sale_price, class: "form-control text-right form-control-sm", value: @product.sale_price.present? ? @product.sale_price : 0 %>
            <div class="input-group-append">
              <%= link_to "#", class: "btn btn-outline-secondary btn-sm" do %>
                <%= fa_icon("tags") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :producer_id %>
      <div class="input-group">
        <%= f.select :producer_id, options_for_select(@producers.collect{|producer| [producer.name, producer.id]}, @product.producer_id.present? ? @product.producer_id : ''), {prompt: "-- Không có nhà sản xuất --"}, { class: "custom-select form-control form-control-sm" } %>
        <div class="input-group-append">
          <%= link_to producers_path, class: "btn btn-outline-secondary btn-sm", remote: true do %>
            <%= fa_icon("ellipsis-h") %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-6">
    <div class="images">
      <div class="upload-images row m-0">
        <div class="preview-image-container-big" id="preview-image-1">

        </div>

        <div class="col row">
          <div class="preview-image-container" id="preview-image-2">

          </div>

          <div class="preview-image-container" id="preview-image-3">

          </div>

          <div class="preview-image-container" id="preview-image-4">

          </div>

          <div class="preview-image-container" id="preview-image-5">

          </div>
        </div>

      </div>

      <div class="form-group">
        <div class="custom-file">
          <%= f.file_field :images, multiple: true, direct_upload: true, class: "custom-file-input", lang: "vi" %>
          <label class="custom-file-label" for="customFile">Chọn nhiều ảnh (tối đa 5 ảnh)</label>
        </div>
      </div>
    </div>

    <div class="manage-stock">
      <div class="form-group row">
        <%= f.label :in_stock, class: "col-md-6 mt-1" %>
        <div class="col-md-6">
          <%= f.number_field :in_stock, class: "form-control form-control-sm text-right", value: @product.in_stock.present? ? @product.in_stock : 0 %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :in_stock_min, class: "col-md-6 mt-1" %>
        <div class="col-md-6">
          <%= f.number_field :in_stock_min, class: "form-control form-control-sm text-right", value: @product.in_stock_min.present? ? @product.in_stock_min : 0 %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :in_stock_max, class: "col-md-6 mt-1" %>
        <div class="col-md-6">
          <%= f.number_field :in_stock_max, class: "form-control form-control-sm text-right", value: @product.in_stock_max.present? ? @product.in_stock_max : 999999999 %>
        </div>
      </div>
    </div>

  </div>

  <%= f.button t(:save_only), type: 'submit', name: 'kind', value: 'save', class: 'd-none', id: 'save_only_product' %>
  <%= f.button t(:save_cont), type: 'submit', name: 'kind', value: 'cont', class: 'd-none', id: 'save_product_and_add_new' %>
</div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header" id="header-property">
        <%= link_to "#collapseProperty", 'data-toggle': "collapse", 'aria-expanded': "true", class: "btn btn-link p-0 font-weight-bold" do %>
          Theo dõi thuộc tính (Màu sắc, kích thước, ...)
        <% end %>
        <div class="float-right">
          <i class="fa" aria-hidden="true"></i>
        </div>
      </div>
      <div class="collapse" aria-labelledby="header-property" id="collapseProperty">
        <div class="card-body">
          Property
        </div>
      </div>

    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <div class="card">
      <div class="card-header" id="header-unit">
        <%= link_to "#collapseUnit", 'data-toggle': "collapse", 'aria-expanded': "true", class: "btn btn-link p-0 font-weight-bold" do %>
          Đơn vị tính
        <% end %>
        <div class="float-right">
          <i class="fa" aria-hidden="true"></i>
        </div>
      </div>
      <div class="collapse" aria-labelledby="header-unit" id="collapseUnit">
        <div class="card-body">
          <div class="form-group row">
            <%= f.label :basic_unit, class: "col-1 mt-1" %>
            <div class="col-1">
              <%= f.text_field :basic_unit, class: "form-control form-control-sm" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/products/_new_product_detail.html.erb
<div class="row">
  <div class="col">
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control ckeditor", ckeditor: { toolbar: 'mini' } %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="form-group">
      <%= f.label :note %>
      <%= f.text_area :note, placeholder: "Nhập ghi chú cho hàng hóa của bạn", class: "form-control" %>
    </div>
  </div>
</div>

app/views/products/create.js.erb
<% if @product.errors.present? %>
toastr.error("<%= @product.errors.full_messages.to_sentence %>");
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<% set_meta_tags title: t('activerecord.attributes.product.title'), site: t(:title), reverse: true %>
<div class="products">
  <div class="header">
    <nav class="navbar navbar-expand navbar-light bg-light">
      <div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <span class="title"><%= t('activerecord.attributes.product.title') %></span>
          </li>
        </ul>
      </div>
      <div class="mx-auto order-0">

      </div>
      <div class="navbar-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to new_product_path, class: "btn btn-info header-menu" do %>
              <%= fa_icon "plus", text: t('.add_product') %>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_product_path, class: "btn btn-info header-menu" do %>
              <%= fa_icon "upload", text: "Nhập excel" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_product_path, class: "btn btn-info header-menu" do %>
              <%= fa_icon "download", text: "Xuất excel" %>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <a class="dropdown-toggle btn btn-info header-menu" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "columns" %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>


  <div class="notification">
    <% if @products.size == 0 %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        Chưa có hàng hóa nào trong cửa hàng của bạn. Vui lòng chọn <strong>"Thêm hàng hóa"</strong> để thêm hàng hóa của bạn!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>

  <div class="search">
    <div class="col-md-6">
      <%= search_form_for @q, url: products_path, method: :get do |f| %>
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text"><%= t(:search) %></div>
          </div>
          <%= f.text_field :name_or_code_or_abbr_name_cont, placeholder: t('.search_placeholer'), class: "form-control" %>
          <div class="input-group-append">
            <%= f.submit t(:search), class: "btn btn-info btn-park" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="list">
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
      <th><%= sort_link @q, :code, t('activerecord.attributes.product.code'), default_order: :desc %></th>
      <th><%= sort_link @q, :name, t('activerecord.attributes.product.name') %></th>
      <th><%= t('activerecord.attributes.product.cost_price') %></th>
      <th><%= t('activerecord.attributes.product.sale_price') %></th>
      <th><%= t('activerecord.attributes.product.in_stock_short') %></th>
      <th></th>
      </thead>

      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <%= link_to product.code, product_path(product) %>
          </td>
          <td class="font-weight-bold">
            <%= link_to product.name, product_path(product) %>
          </td>
          <td>
            <%= product.cost_price %>
          </td>
          <td>
            <%= product.sale_price %>
          </td>
          <td>
            <%= product.in_stock %>
          </td>
          <td>
            <%= link_to fa_icon("pencil"), edit_product_path(product) %>
            <%= link_to fa_icon("trash"), product_path(product), method: :delete, class: "text-danger", data: { confirm: "Bạn có chắc chắn muốn xóa hàng hóa này ?" } %>
          </td>
        </tr>
      <% end %>
      </tbody>

      <tfoot>
      <tr>
        <td colspan="6">
          <%= render partial: 'shared/pagination_footer_table', locals: {objects: @products} %>
        </td>
      </tr>
      </tfoot>
    </table>
  </div>

</div>

app/views/products/new.html.erb
<% set_meta_tags title: t('products.index.add_product'), site: t(:title), reverse: true %>
<%= render 'form' %>

app/views/products/show.html.erb
<% set_meta_tags title: @product.name, site: t(:short_title), reverse: true %>
<div class="m-3 product">
  <div class="card">
    <div class="card-header">
      <h5 class="product-name font-weight-bold mb-0"><%= @product.name %></h5>
    </div>
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active">
            <%= fa_icon("info-circle", text: t('.tab_information')) %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link">
            <%= fa_icon("server", text: t('.tab_in_stock_event')) %>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link">
            <%= fa_icon("list-alt", text: t('.tab_in_stock')) %>
          </a>
        </li>

        <li class="nav-item ml-auto">
          <%= link_to edit_product_path(@product), class: "btn btn-success" do %>
            <%= fa_icon "pencil", text: t(:update) %>
          <% end %>

          <% is_active = @product.status.eql?("active") %>
          <%= link_to update_status_product_path(@product, status: is_active ? "inactive" : "active"), class: "btn #{is_active ? "btn-danger" : "btn-success"}", remote: true, 'data-turbolinks': "false" do %>
            <%= fa_icon "lock", text: is_active ? t(:stop_sale) : t(:allow_sale)%>
          <% end %>

          <%= link_to product_path(@product), method: :delete, class: "btn btn-danger", data: { confirm: "Bạn có chắc chắn muốn xóa hàng hóa này ?", remote: true } do %>
            <%= fa_icon "trash", text: t(:delete) %>
          <% end %>

          <%= link_to products_path, class: "btn btn-secondary" do %>
            <%= fa_icon "arrow-left", text: t(:back) %>
          <% end %>
        </li>

      </ul>
    </div>
    <div class="card-body">
      <div class="row mb-3">
        <% if @product.images.present? %>
        <div class="col-md-6 col-sm-6 row">
          <div class="col-10 p-2">
            <%= image_tag @product.images.first.variant(resize: '320x320'), class: 'img-fluid product-show-image-big' %>
          </div>

          <div class="col-2 p-2">
            <% @product.images.each do |image| %>
              <%= image_tag image.variant(size: '320x320'), class: 'img-fluid img-thumbnail product-show-image-icon' %>
            <% end %>
          </div>
        </div>
        <% end %>

        <div class="col-md-6 col-sm-6">
          <div class="row">
            <div class="col">
              <%= fa_icon "check", class: "text-success", text: "Được bán trực tiếp," %>
              <%= fa_icon "times", class: "text-danger", text: "Không tích điểm" %>
            </div>

          </div>

          <hr>

          <div class="row">
            <div class="col-4"><%= t('activerecord.attributes.product.code') %></div>
            <div class="col-8 font-weight-bold"><%= @product.code %></div>
          </div>

          <hr>

          <% if @product.product_group %>
          <div class="row">
            <div class="col-4"><%= t('activerecord.attributes.product.product_group_id') %></div>
            <div class="col-8"><%= @product.product_group.name %></div>
          </div>
          <hr>
          <% end %>

          <div class="row">
            <div class="col-4"><%= t('activerecord.attributes.product.sale_price') %></div>
            <div class="col-8"><%= number_to_currency @product.sale_price, locale: :vi, precision: 0, delimiter: ' ' %></div>
          </div>

          <hr>

          <div class="row">
            <div class="col-4"><%= t('activerecord.attributes.product.cost_price') %></div>
            <div class="col-8"><%= number_to_currency @product.cost_price, locale: :vi, precision: 0, delimiter: ' ' %></div>
          </div>

          <hr>

          <div class="row">
            <div class="col-4"><%= t('activerecord.attributes.product.in_stock_range') %></div>
            <div class="col-8"><%= @product.in_stock_min %> -> <%= @product.in_stock_max %></div>
          </div>

          <hr>

          <% if @product.producer %>
          <div class="row">
            <div class="col-4"><%= t('activerecord.attributes.product.producer_id') %></div>
            <div class="col-8"><%= @product.producer.name %></div>
          </div>
          <% end %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col">
          <label><%= t('activerecord.attributes.product.description') %></label> <br>
          <%= @product.description.present? ? @product.description : t(:not_update) %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col">
          <label><%= t('activerecord.attributes.product.note') %></label> <br>
          <%= @product.note.present? ? @product.note : t(:not_update) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/update_status.js.erb
<% if @product.errors.present? %>
toastr.error("<%= @product.errors.full_messages.to_sentence %>");
<% else %>
window.location.reload();
<% end %>